# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_min_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
parchment_version=2023.09.03-1.20.1

forge_version=47.1.3
forge_version_range=[47,)
loader_version_range=[46,)


mod_id=bountifulfares
mod_name=Bountiful Fares
mod_name_s=bountifulfares
mod_version=1.3.0-1.20.1
mod_base_package=net.hecco.bountifulfares
mod_authors=[Author]Hecco, [Porter]joe_vettek(jianzoushihu)

mod_license=ARR
mod_description=
mod_update_json=
mod_url=